name: GitHub Actions CRC Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Your-Job-Name:
    runs-on: ubuntu-latest
    steps:
      # figure out how to clone the repo in pipeline runner
      - run: echo "this should clone repo"
      # figure out how to install python in required version
      - run: echo "this should install python in version that is needed for our app"
      # figure out how to install requirements for our project
      - run: echo "this should install all needed packages on runner"
      # figure out how to run tests to see if the server works
      - run: echo "this should launch test and fail the pipeline if tests fail"
