name: GitHub Actions CRC Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  # this will ignore all pushes to tags, but will trigger on every new commit
  # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore
  push:
    tags-ignore:
      - '**'
    branches:
      - "**"

jobs:
  calculate-tag-and-release:
    steps:
      - run: |
          echo "using pipe char `|` allows us to write multiline script"
          echo "this should probably checkout the repo first, and install some tool to calculate the version automatically"
          echo "let's use `gitverion` provided by `gittools` to calculate it"
          echo "lastly let's create the git tag, push new tag and create a release"
  Run-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      # figure out how to clone the repo in pipeline runner
      - name: Check out repository code
        uses: actions/checkout@v4
      # figure out how to install python in required version
      - name: Set up Python 3.11.5
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.5"
      # figure out how to install requirements for our project
      - run: python -m pip install -r requirements.txt
      # figure out how to run tests to see if the server works
      - run: python -m unittest -v
