name: GitHub Actions CRC Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Run-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      # figure out how to clone the repo in pipeline runner
      - name: Check out repository code
        uses: actions/checkout@v4
      # figure out how to install python in required version
      - name: Set up Python 3.11.5
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.5"
      # figure out how to install requirements for our project
      - run: python -m pip install -r requirements.txt
      # figure out how to run tests to see if the server works
      - run: python -m unittest -v
