name: GitHub Actions CRC Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  # this will ignore all pushes to tags, but will trigger on every new commit
  # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore
  push:
    tags-ignore:
      - '**'
    branches:
      - "**"

jobs:
  calculate-tag-and-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full git history is fetched
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: "6.0.5"
      - name: Determine Version
        id: version_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v3.1.11
      - name: Create new tag
        run: |
          new_tag=v${{ steps.version_step.outputs.SemVer }}
          git tag $new_tag
          git push origin $new_tag
      - name: Create GitHub release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.version_step.outputs.SemVer }}
          release_name: Release ${{ steps.version_step.outputs.SemVer }}
          body: "Automated release based on the latest commit."
          draft: false
          prerelease: false
  Run-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      # figure out how to clone the repo in pipeline runner
      - name: Check out repository code
        uses: actions/checkout@v4
      # figure out how to install python in required version
      - name: Set up Python 3.11.5
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.5"
      # figure out how to install requirements for our project
      - run: python -m pip install -r requirements.txt
      # figure out how to run tests to see if the server works
      - run: python -m unittest -v
